name: CI
permissions:
  contents: read

on:
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron:  '0 0 * * *'

jobs:
  validate:
    name: hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: check out the repository
        uses: actions/checkout@v5
      - name: hassfest validation
        uses: home-assistant/actions/hassfest@master

  hacs:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - name: validate
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands

  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: "3.13"
    - name: set PY
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v3.0.1

  tests:
    runs-on: ubuntu-latest
    name: pytest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements-test.txt
      - name: Run pytest
        run: |
          pytest
