name: CI

on:
  push:
  pull_request:
  schedule:
  - cron:  '0 0 * * *'

jobs:
  validate:
    name: hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: check out the repository
        uses: actions/checkout@v3
      - name: hassfest validation
        uses: home-assistant/actions/hassfest@master
