name: CI

on:
  push:
  pull_request:
  schedule:
  - cron:  '0 0 * * *'

jobs:
  validate:
    name: hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: check out the repository
        uses: actions/checkout@v3
      - name: hassfest validation
        uses: home-assistant/actions/hassfest@master

  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: set PY
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v3.0.0
